# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import physics_room_pb2 as physics__room__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in physics_room_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PhysicsRoomServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/physicsroom.v1.PhysicsRoomService/StartSession',
                request_serializer=physics__room__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=physics__room__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.TickRun = channel.unary_unary(
                '/physicsroom.v1.PhysicsRoomService/TickRun',
                request_serializer=physics__room__pb2.TickRunRequest.SerializeToString,
                response_deserializer=physics__room__pb2.TickRunResponse.FromString,
                _registered_method=True)
        self.GetSessionState = channel.unary_unary(
                '/physicsroom.v1.PhysicsRoomService/GetSessionState',
                request_serializer=physics__room__pb2.GetSessionStateRequest.SerializeToString,
                response_deserializer=physics__room__pb2.GetSessionStateResponse.FromString,
                _registered_method=True)
        self.GetSessionEvents = channel.unary_unary(
                '/physicsroom.v1.PhysicsRoomService/GetSessionEvents',
                request_serializer=physics__room__pb2.GetSessionEventsRequest.SerializeToString,
                response_deserializer=physics__room__pb2.GetSessionEventsResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/physicsroom.v1.PhysicsRoomService/StreamEvents',
                request_serializer=physics__room__pb2.GetSessionEventsRequest.SerializeToString,
                response_deserializer=physics__room__pb2.EventEnvelope.FromString,
                _registered_method=True)


class PhysicsRoomServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TickRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhysicsRoomServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=physics__room__pb2.StartSessionRequest.FromString,
                    response_serializer=physics__room__pb2.StartSessionResponse.SerializeToString,
            ),
            'TickRun': grpc.unary_unary_rpc_method_handler(
                    servicer.TickRun,
                    request_deserializer=physics__room__pb2.TickRunRequest.FromString,
                    response_serializer=physics__room__pb2.TickRunResponse.SerializeToString,
            ),
            'GetSessionState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionState,
                    request_deserializer=physics__room__pb2.GetSessionStateRequest.FromString,
                    response_serializer=physics__room__pb2.GetSessionStateResponse.SerializeToString,
            ),
            'GetSessionEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionEvents,
                    request_deserializer=physics__room__pb2.GetSessionEventsRequest.FromString,
                    response_serializer=physics__room__pb2.GetSessionEventsResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=physics__room__pb2.GetSessionEventsRequest.FromString,
                    response_serializer=physics__room__pb2.EventEnvelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physicsroom.v1.PhysicsRoomService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physicsroom.v1.PhysicsRoomService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PhysicsRoomService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsroom.v1.PhysicsRoomService/StartSession',
            physics__room__pb2.StartSessionRequest.SerializeToString,
            physics__room__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TickRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsroom.v1.PhysicsRoomService/TickRun',
            physics__room__pb2.TickRunRequest.SerializeToString,
            physics__room__pb2.TickRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsroom.v1.PhysicsRoomService/GetSessionState',
            physics__room__pb2.GetSessionStateRequest.SerializeToString,
            physics__room__pb2.GetSessionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsroom.v1.PhysicsRoomService/GetSessionEvents',
            physics__room__pb2.GetSessionEventsRequest.SerializeToString,
            physics__room__pb2.GetSessionEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/physicsroom.v1.PhysicsRoomService/StreamEvents',
            physics__room__pb2.GetSessionEventsRequest.SerializeToString,
            physics__room__pb2.EventEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
